### ISSUE TITLE
[Autopar-Clava] Can you provide the script use in the publication

### ISSUE THREAD

**Issue by kira42310** [specs-feup/clava#141]
Hello

Can you provide the right script use in this publication? [link](https://dl.acm.org/doi/abs/10.1145/3183767.3183770?casa_token=Ntl0IU99sVMAAAAA:Vj5vNCj-DYb8V-rKvrJX-9wrtGs56QAPIho7SAESFrHYdkaY2cck3JCmSxoXFjByN6XNgOStsvY8)

I use the script from this issue [ref](https://github.com/specs-feup/clava/issues/58#issuecomment-1116455253). But ICC fail to compile 3 out of 8 benchmarks from NPB.

**Comment by joaobispo** [comment]
Hello, what kind of errors is ICC outputting?

**Comment by kira42310** [comment]
This is the MG benchmark error. Basically, Clava just annotate the wrong thing out.
```
mg.cpp(122): warning #161: unrecognized #pragma
     #pragma parallelize_id 0x562e7e5520a8_1
             ^

mg.cpp(171): warning #161: unrecognized #pragma
        #pragma parallelize_id 0x562e7e555e58_1
                ^

mg.cpp(188): warning #161: unrecognized #pragma
        #pragma parallelize_id 0x562e7e556678_1
                ^
...
```

This is the SP benchmark error. The reduction clause has cause errors.
```
sp.cpp(751): error: array section length must be specified for incomplete array types
     #pragma omp parallel for default(shared) private(k, j, i, m, zeta, eta, xi, add) firstprivate(dnzm1, dnym1, dnxm1, grid_points, ce, u, u_exact) reduction(+ : rms[:])
                                                                                                                                                                       ^

sp.cpp(1461): error: array section length must be specified for incomplete array types
     #pragma omp parallel for default(shared) private(k, j, i, m, add) firstprivate(nz2, ny2, nx2, rhs) reduction(+ : rms[:])
                                                                                                                          ^
```

And the LU also have the same problems
```
lu.cpp(1356): error: array section length must be specified for incomplete array types
     #pragma omp parallel for default(shared) private(k, j, i, m) firstprivate(nz0, jst, jend, ist, iend, v) reduction(+ : sum[:])
                                                                                                                               ^
```

I use source code from this repository, in case you want to know too.[link](https://github.com/GMAP/NPB-CPP)

**Comment by joaobispo** [comment]
Ok, we have setup continuous integration for AutoPar and NAS benchmarks, I will tell you the steps to replicate it in Linux:

- Make sure you have Java 20 (minimum), CMake and build-essential

- Download [clava-update](specs.fe.up.pt/tools/clava/clava-update) script to a folder that is in the system's path, give it execution permissions and run it with `sudo` so that it installs Clava CMake plugin

- Checkout the [specs-lara](https://github.com/specs-feup/specs-lara) repository

- Go to folder `specs-lara/ANTAREX/AutoPar/NAS`, create a folder `build`, enter it, call `cmake ..` and it should call AutoPar for the NAS benchmarks that we used for the publication.

You can check the version of the NAS benchmarks we used by checking the folders in `specs-lara/ANTAREX/AutoPar/NAS`, and after running CMake, the code with the pragmas should be in folders such as `build/NAS/EP/ep_w_clava_weave/woven`

Please tell us if this worked for you.

**Comment by joaobispo** [comment]
There was no feedbak for two weeks, I'm closing this issue.

**Comment by kira42310** [comment]
Sorry for the late reply, but I just have the time to test it. I have two questions.

First. Where did you get the NPB and Polybench source code? For the NPB I caanot find the official C source code from their website, their only fortran code. Do you port the code by yourself?

Second. When I run the `cmake ..` it has an error during analyze 2mm from Polybench. This is the error.
```
Exception in thread "main" java.lang.RuntimeException: Exception while executing LARA script
        at larai.LaraI.execPrivate(Unknown Source)
        at larai.LaraI.lambda$exec$3(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Exception during interpretation
        at larai.LaraI.execPrivate(Unknown Source)
        ... 6 more
Caused by: org.lara.interpreter.exception.EvaluationException: Exception when evaluating javascript
        at org.lara.interpreter.Interpreter.evaluate(Unknown Source)
        at org.lara.interpreter.Interpreter.executeMainAspect(Unknown Source)
        at larai.LaraI.interpret(Unknown Source)
        ... 7 more
Caused by: java.lang.RuntimeException: Polyglot exception while evaluating JavaScript code
        at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(Unknown Source)
        at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(Unknown Source)
        at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(Unknown Source)
        ... 10 more
Caused by: org.graalvm.polyglot.PolyglotException: Error:
Execution error in CheckOpenMPPragmas.lara:4:1:55:3, line 47:Cannot read property "toString" from undefined
        at <js>.CheckOpenMPPragmas.call(/data/ssd2t/mudang/other_autopar/clava-new/specs-lara-master/ANTAREX/AutoPar/Polybench/2mm/../CheckOpenMPPragmas.lara->js:143)
        at <js>.:program(/data/ssd2t/mudang/other_autopar/clava-new/specs-lara-master/ANTAREX/AutoPar/Polybench/2mm/../CheckOpenMPPragmas.lara->js:166)
        at org.graalvm.polyglot.Context.eval(Context.java:399)
        ... 13 more
```

**Comment by joaobispo** [comment]
1. For NPB, the code is based on a port by a research group of [Seoul National University (SNU)](https://en.snu.ac.kr/), called [SNU NPB](https://thunder.snu.ac.kr/?page_id=64&page=7). Polybench, if I recall correctly, is based on version 4.2, probably [this one](https://sourceforge.net/projects/polybench/).

2. This is an issue that was detected, it has to do with a bug in the current version of the LARA framework where for .lara files, arguments are not being communicated correctly (hence the `undefined`). This bug is not happening when .js files are used, and since .lara files are legacy, fixing this is not a priority. However, I applied the same "fix" I did with NAS, and disabled the part of the code that used the input arguments, which verified if the generated code is according to what was expected.

**Comment by kira42310** [comment]
If the .lara file has a problems, can you show me or explain how to transform .lara script to .js script or if you can transform it for me, for the correctness of the results. Just for NPB is ok.

And thank you for telling me where you get the source code.

**Comment by joaobispo** [comment]
The .lara scripts have been translated to .js scripts, it should work now with checks. For an example of LARA->JS translation, check [this](https://github.com/specs-feup/specs-lara/commit/ee2f0464120798527d06b9057bc63b08a9aee570#diff-9f2f2b129ad0b51a06ade3cb055ce61048536b64c2229a79440966b5fc5e7d6c).
