### ISSUE TITLE
Question: How to avoid the download of resources?

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#23]
Upon first invocation clava downloads: `clang_ast_v*.zip`, `clang_builtin_includes_v*.zip`, `libc_cxx.zip` into `/tmp/clang_ast_exe*`

Can I somehow avoid this. I noticed there's this flag.
```
 -cr,--custom-resources                                 Enables custom resource files (e.g., clang_ast.resources)
```

I tried to feed it a file

```
==> clang_ast.resources <==
# Resources for ClangAst Dumper

BUILTIN_INCLUDES_3_8 =
LIBC_CXX_WINDOWS =
LIBC_CXX_MAC_OS =
WIN_EXE =
WIN_DLL1 =
WIN_DLL2 =
WIN_DLL3 =
LINUX_EXE = /tmp/clang_ast_exe_piotr/
CENTOS6_EXE =
MAC_OS_EXE =
```

but it somehow ignored me. Does the option even accept a file?

**Comment by joaobispo** [comment]
Nice catch, sadly this is a feature that is currently not implemented.

However, there is a way to avoid downloading resources.  if you put the `clang_ast_exe` folder next to the Clava JAR file it should use those files, instead of downloading them. To check if the local version is being used, a message of this kind should appear:

```Using local version of ClangAstDumper (<PATH_TO_EXE>). Option 'use platform includes' will be ignored```

**Comment by ppietrasa** [comment]
It worked! This will do. Thanks!
